# Generated by Django 4.2.16 on 2024-11-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Typhoid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=100)),
                ('disease_symptoms', models.TextField()),
                ('disease_photos', models.ImageField(upload_to='symptoms/Typhoid')),
            ],
        ),
    ]
