# Generated by Django 4.2.16 on 2024-11-22 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0002_typhoid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typhoid',
            name='disease_photos',
        ),
        migrations.CreateModel(
            name='TyphoidPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='symptomes/Typhoid')),
                ('ugonjwa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='healthcare.ugonjwa')),
            ],
        ),
    ]
