# Generated by Django 4.2.16 on 2024-11-22 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0003_remove_typhoid_disease_photos_typhoidphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typhoidphoto',
            name='ugonjwa',
        ),
        migrations.AddField(
            model_name='typhoid',
            name='typhoi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='typhoidphoto',
            name='typhoid',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='healthcare.typhoid'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='typhoidphoto',
            name='photo',
            field=models.ImageField(upload_to='symptoms/Typhoid'),
        ),
    ]
