# Generated by Django 4.2.16 on 2024-11-24 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0006_ailment_picha_delete_symptom_ailment_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ailment',
            name='images',
        ),
    ]
