# Generated by Django 4.2.16 on 2024-11-24 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0007_remove_ailment_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picha',
            name='image',
        ),
    ]
