# Generated by Django 4.2.16 on 2024-12-12 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0020_alter_customuser_options_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
