# Generated by Django 4.2.16 on 2024-12-12 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0022_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
